dist: precise
language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls
addons:
  hosts:
    - example.com
  hostname: example.com
